---
language: python
python:
  - 3.8

services: docker

env:
  global:
    - ORG_NAME: verdaccio
    - ROLE_NAME: verdaccio
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash # yamllint disable-line

install:
  - curl https://gist.githubusercontent.com/030/fa2454b56c525286b39d549583173d8e/raw/c9f9cf439339819958e13cad1d5b5f719217d427/ansible-ci-requirements.sh | sudo bash  # yamllint disable-line rule:line-length

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME $ORG_NAME.$ROLE_NAME
  - cd $ORG_NAME.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
